// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package accounting

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Account struct {
	ID            int32
	Name          sql.NullString
	AccountNumber sql.NullInt32
	RoutingNumber sql.NullInt32
	BankID        sql.NullInt32
	Type          sql.NullInt32
	CountryID     sql.NullBool
	CompanyID     sql.NullInt32
	Postable      sql.NullBool
	IsActive      sql.NullBool
	Meta          sql.NullString
	CreatedBy     sql.NullInt32
	CreatedAt     sql.NullTime
	ModifiedBy    sql.NullInt32
	ModifiedAt    sql.NullTime
}

type AccountPayable struct {
	ID         int32
	PoNumber   sql.NullTime
	Vendor     sql.NullInt32
	Amount     sql.NullString
	Currency   sql.NullString
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type AccountReceivable struct {
	ID         int32
	Amount     sql.NullString
	Currency   sql.NullString
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Bank struct {
	ID         int32
	Name       sql.NullString
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Bill struct {
	ID          int32
	Date        sql.NullTime
	Amount      sql.NullString
	Currency    sql.NullString
	Vendor      sql.NullInt32
	Particulars sql.NullString
	Meta        sql.NullString
	CreatedBy   sql.NullInt32
	CreatedAt   sql.NullTime
	ModifiedBy  sql.NullInt32
	ModifiedAt  sql.NullTime
}

type Budget struct {
	ID           int32
	Name         sql.NullString
	Amount       sql.NullString
	CurrencyID   sql.NullInt32
	ProductionID sql.NullInt32
	Meta         sql.NullString
	CreatedBy    sql.NullInt32
	CreatedAt    sql.NullTime
	ModifiedBy   sql.NullInt32
	ModifiedAt   sql.NullTime
}

type Company struct {
	ID         int32
	Name       sql.NullString
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Country struct {
	ID         int32
	Name       sql.NullString
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Currency struct {
	ID         int32
	Name       sql.NullString
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Journal struct {
	ID         int32
	Date       sql.NullTime
	EntryType  sql.NullBool
	PaymentID  sql.NullInt32
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Location struct {
	ID         int32
	Name       sql.NullString
	StateID    sql.NullInt32
	CountryID  sql.NullInt32
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Payment struct {
	ID                   int32
	Date                 sql.NullTime
	PaymentType          sql.NullString
	BillID               sql.NullInt32
	PayrollID            sql.NullInt32
	Amount               sql.NullString
	Currency             sql.NullString
	AccountID            sql.NullInt32
	BudgetID             sql.NullInt32
	LocationID           sql.NullInt32
	ReconciliationStatus sql.NullInt32
	Meta                 sql.NullString
	CreatedBy            sql.NullInt32
	CreatedAt            sql.NullTime
	ModifiedBy           sql.NullInt32
	ModifiedAt           sql.NullTime
}

type PaymentType struct {
	ID         int32
	Type       sql.NullString
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Payroll struct {
	ID                int32
	PaymentType       sql.NullString
	EmployeeFirstName sql.NullInt32
	EmployeeLastName  sql.NullInt32
	EmployeeID        sql.NullInt32
	Amount            sql.NullString
	CurrencyID        sql.NullInt32
	Meta              sql.NullString
	CreatedBy         sql.NullInt32
	CreatedAt         sql.NullTime
	ModifiedBy        sql.NullInt32
	ModifiedAt        sql.NullTime
}

type Permission struct {
	ID             int32
	Name           sql.NullString
	PermissionType sql.NullInt32
	Meta           sql.NullString
	CreatedBy      sql.NullInt32
	CreatedAt      sql.NullTime
	ModifiedBy     sql.NullInt32
	ModifiedAt     sql.NullTime
}

type PermissionType struct {
	ID             int32
	PermissionType sql.NullString
	Meta           sql.NullString
	CreatedBy      sql.NullInt32
	CreatedAt      sql.NullTime
	ModifiedBy     sql.NullInt32
	ModifiedAt     sql.NullTime
}

type PettyCash struct {
	ID          int32
	PaymentType sql.NullString
	Amount      sql.NullString
	Currency    sql.NullString
	AccountID   sql.NullInt32
	Meta        sql.NullString
	CreatedBy   sql.NullInt32
	CreatedAt   sql.NullTime
	ModifiedBy  sql.NullInt32
	ModifiedAt  sql.NullTime
}

type Production struct {
	ID                int32
	Name              sql.NullString
	CompanyID         sql.NullInt32
	DefaultSetID      sql.NullInt32
	DefaultLocationID sql.NullInt32
	DefaultSeriesID   sql.NullInt32
	IsActive          sql.NullBool
	Meta              sql.NullString
	CreatedBy         sql.NullInt32
	CreatedAt         sql.NullTime
	ModifiedBy        sql.NullInt32
	ModifiedAt        sql.NullTime
}

type PurchaseOrder struct {
	ID                int32
	PoNumber          sql.NullInt32
	PoDate            sql.NullTime
	Amount            sql.NullString
	Currency          sql.NullString
	ProductionID      sql.NullInt32
	Approver1ID       sql.NullInt32
	Approver1Date     sql.NullTime
	Approver1Comments sql.NullString
	Approver2ID       sql.NullInt32
	Approver2Date     sql.NullTime
	Approver2Comments sql.NullString
	Approver3ID       sql.NullInt32
	Approver3Date     sql.NullTime
	Approver3Comments sql.NullString
	Meta              sql.NullString
	CreatedBy         sql.NullInt32
	CreatedAt         sql.NullTime
	ModifiedBy        sql.NullInt32
	ModifiedAt        sql.NullTime
}

type Series struct {
	ID         int32
	Name       sql.NullString
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Set struct {
	ID         int32
	Name       sql.NullString
	LocationID sql.NullInt32
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type State struct {
	ID         int32
	Name       sql.NullString
	ContryID   sql.NullInt32
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type Tenant struct {
	ID         int32
	Name       sql.NullInt32
	CompanyID  sql.NullInt32
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}

type User struct {
	ID           int32
	FirstName    sql.NullString
	LastName     sql.NullString
	Email        sql.NullString
	Phone        sql.NullString
	Dob          sql.NullTime
	Username     sql.NullString
	Password     sql.NullString
	ProfileImage sql.NullString
	Address      sql.NullString
	IsActive     sql.NullBool
	CompanyID    sql.NullInt32
	Meta         pqtype.NullRawMessage
	CreatedBy    sql.NullInt32
	CreatedAt    sql.NullTime
	ModifiedBy   sql.NullInt32
	ModifiedAt   sql.NullTime
}

type UserPermission struct {
	ID           int32
	UserID       sql.NullInt32
	PermissionID sql.NullInt32
	Meta         sql.NullString
	CreatedBy    sql.NullInt32
	CreatedAt    sql.NullTime
	ModifiedBy   sql.NullInt32
	ModifiedAt   sql.NullTime
}

type Vendor struct {
	ID         int32
	Name       sql.NullString
	IsActive   sql.NullBool
	Meta       sql.NullString
	CreatedBy  sql.NullInt32
	CreatedAt  sql.NullTime
	ModifiedBy sql.NullInt32
	ModifiedAt sql.NullTime
}
